//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    // Adding data annotations change the appearance 
    using System.ComponentModel.DataAnnotations;

    public partial class Enrollment
    {
        Student student = new Student();
        public int EnrollmentID { get; set; }
        // Put a space between GradePercentage column
        [Display(Name = "Grade Percentage")]
        public Nullable<decimal> GradePercentage { get; set; }
        // Put a space between the LetterGrade column
        [Display(Name = "Letter Grade")]
        public string LetterGrade
        {
            //Read only property. No reason to set the letter grade
            get
            {
                // Set the letter grade scale with conditional statements 
                string result;
                if (GradePercentage >= 90)
                {
                    result = "A";
                }

                else if (GradePercentage >= 80)
                {
                    result = "B";
                }

                else if (GradePercentage >= 70)
                {
                    result = "C";
                }

                else if (GradePercentage >= 60)
                {
                    result = "D";
                }

                else
                {
                    result = "F";
                }
                return result;
            }
            set { }
        }

        public int CourseID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
