//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enrollment
    {
        Student student = new Student();
        public int EnrollmentID { get; set; }
        [Display(Name = "Grade Percentage")]
        public Nullable<decimal> GradePercentage { get; set; }
        [Display(Name = "Letter Grade")]
        public string LetterGrade
        {
            //Read only property. No reason to set the letter grade
            get
            {
                string result;
                if (GradePercentage >= 90)
                {
                    //Might want to use the math.round to round up 89.5 for example 
                    result = "A";
                }

                else if (GradePercentage >= 80)
                {
                    result = "B";
                }

                else if (GradePercentage >= 70)
                {
                    result = "C";
                }

                else if (GradePercentage >= 60)
                {
                    result = "D";
                }

                else
                {
                    result = "F";
                }
                return result;
            }
            set { }
        }

        public int CourseID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
